// Authentication USING OAUTH
export const LOGIN_WITH_OAUTH_LOADING = "LOGIN_WITH_OAUTH_LOADING";
export const LOGIN_WITH_OAUTH_SUCCESS = "LOGIN_WITH_OAUTH_SUCCESS";
export const LOGIN_WITH_OAUTH_FAIL = "LOGIN_WITH_OAUTH_FAIL";

// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// Login Using Email
export const LOGIN_WITH_EMAIL_LOADING = "LOGIN_WITH_EMAIL_LOADING";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAIL = "LOGIN_WITH_EMAIL_FAIL";

// Register Using Email
export const REGISTER_WITH_EMAIL_LOADING = "REGISTER_WITH_EMAIL_LOADING";
export const REGISTER_WITH_EMAIL_SUCCESS = "REGISTER_WITH_EMAIL_SUCCESS";
export const REGISTER_WITH_EMAIL_FAIL = "REGISTER_WITH_EMAIL_FAIL";
export const RESET_EMAIL_SUCCESS_MESSAGE = "RESET_EMAIL_SUCCESS_MESSAGE";

// Me Loading
export const ME_LOADING = "ME_LOADING";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAIL = "ME_FAIL";

export const GET_FEATURE = "GET_FEATURE";
export const GET_PROFILE = "GET_PROFILE";

export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const EDIT_USER_LOADING = "EDIT_USER_LOADING";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// Post solution
export const POST_SOLUTION_REQUEST = "POST_SOLUTION_REQUEST";
export const POST_SOLUTION_SUCCESS = "POST_SOLUTION_SUCCESS";
export const POST_SOLUTION_FAIL = "POST_SOLUTION_FAIL";

//Update solution
export const UPDATE_SOLUTION_REQUEST = "UPDATE_SOLUTION_REQUEST";
export const UPDATE_SOLUTION_SUCCESS = "UPDATE_SOLUTION_SUCCESS";
export const UPDATE_SOLUTION_FAIL = "UPDATE_SOLUTION_FAIL";

//Delete solution
export const DELETE_SOLUTION_REQUEST = "DELETE_SOLUTION_REQUEST";
export const DELETE_SOLUTION_SUCCESS = "DELETE_SOLUTION_SUCCESS";
export const DELETE_SOLUTION_FAIL = "DELETE_SOLUTION_FAIL";

// Questions
export const ASK_QUESTION_LOADING = "ASK_QUESTION_LOADING";
export const ASK_QUESTION_SUCCESS = "ASK_QUESTION_SUCCESS";
export const ASK_QUESTION_FAIL = "ASK_QUESTION_FAIL";

// Search Questions
export const SEARCH_QUESTION_LOADING = "SEARCH_QUESTION_LOADING";
export const SEARCH_QUESTION_SUCCESS = "SEARCH_QUESTION_SUCCESS";
export const SEARCH_QUESTION_FAIL = "SEARCH_QUESTION_FAIL";

// Tags
export const GET_ALL_TAGS_LOADING = "GET_ALL_TAGS_LOADING";
export const GET_ALL_TAGS_SUCCESS = "GET_ALL_TAGS_SUCCESS";
export const GET_ALL_TAGS_FAIL = "GET_ALL_TAGS_FAIL";

//Get Category
export const GET_ALL_CATEGORY_LOADING = "GET_ALL_CATEGORY_LOADING";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

// view solution
export const VIEW_SOLUTION_LOADING = "VIEW_SOLUTION_LOADING";
export const VIEW_SOLUTION_SUCCESS = "VIEW_SOLUTION_SUCCESS";
export const VIEW_SOLUTION_FAIL = "VIEW_SOLUTION_FAIL";

//all solutions
export const GET_ALL_SOLUTIONS_LOADING = "GET_ALL_SOLUTIONS_LOADING";
export const GET_ALL_SOLUTIONS_SUCCESS = "GET_ALL_SOLUTIONS_SUCCESS";
export const GET_ALL_SOLUTIONS_FAIL = "GET_ALL_SOLUTIONS_FAIL";

// All Questions
export const GET_ALL_QUESTIONS_LOADING = "GET_ALL_QUESTIONS_LOADING";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS";
export const GET_ALL_QUESTIONS_FAIL = "GET_ALL_QUESTIONS_FAIL";

// UpVote & DownVote Solution in Solution Page
export const UPVOTE_SOLUTION_LOADING = "UPVOTE_SOLUTION_LOADING";
export const UPVOTE_SOLUTION_SUCCESS = "UPVOTE_SOLUTION_SUCCESS";
export const UPVOTE_SOLUTION_FAIL = "UPVOTE_SOLUTION_FAIL";
export const DOWNVOTE_SOLUTION_LOADING = "DOWNVOTE_SOLUTION_LOADING";
export const DOWNVOTE_SOLUTION_SUCCESS = "DOWNVOTE_SOLUTION_SUCCESS";
export const DOWNVOTE_SOLUTION_FAIL = "DOWNVOTE_SOLUTION_FAIL";

// Solution View Page, Add Comment, update comment, delete comment
export const ADD_COMMENT_LOADING = "ADD_COMMENT_LOADING";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const UPDATE_COMMENT_LOADING = "UPDATE_COMMENT_LOADING";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";

export const DELETE_COMMENT_LOADING = "DELETE_COMMENT_LOADING";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

// Followers
export const GET_FOLLOWERS_LOADING = "GET_FOLLOWERS_LOADING";
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS";
export const GET_FOLLOWERS_FAIL = "GET_FOLLOWERS_FAIL";

//Intrsted Categories
export const INTERESTED_CATEGORYS_LOADING = "INTERESTED_CATEGORYS_LOADING";
export const INTERESTED_CATEGORYS_SUCCESS = "INTERESTED_CATEGORYS_SUCCESS";
export const INTERESTED_CATEGORYS_FAIL = "INTERESTED_CATEGORYS_FAIL";

// Follow Unfollow user
export const FOLLOW_UNFOLLOW_USER_LOADING = "FOLLOW_UNFOLLOW_USER_LOADING";
export const FOLLOW_UNFOLLOW_USER_SUCCESS = "FOLLOW_UNFOLLOW_USER_SUCCESS";
export const FOLLOW_UNFOLLOW_USER_FAIL = "FOLLOW_UNFOLLOW_USER_FAIL";

//report user
export const REPORT_USER_LOADING = "REPORT_USER_LOADING";
export const REPORT_USER_SUCCESS = "REPORT_USER_SUCCESS";
export const REPORT_USER_FAIL = "REPORT_USER_FAIL";

// Report Question
export const REPORT_QUESTION_LOADING = "REPORT_QUESTION_LOADING";
export const REPORT_QUESTION_SUCCESS = "REPORT_QUESTION_SUCCESS";
export const REPORT_QUESTION_FAIL = "REPORT_QUESTION_FAIL";

// Authenticated User View My Followings
export const VIEW_MY_FOLLOWINGS_LOADING = "VIEW_MY_FOLLOWINGS_LOADING";
export const VIEW_MY_FOLLOWINGS_SUCCESS = "VIEW_MY_FOLLOWINGS_SUCCESS";
export const VIEW_MY_FOLLOWINGS_FAIL = "VIEW_MY_FOLLOWINGS_FAIL";

// Follow Unfollow Any User
export const FOLLOW_UNFOLLOW_ANY_USER_SUCCESS =
  "FOLLOW_UNFOLLOW_ANY_USER_SUCCESS";

// TOggle Bookmark
export const TOGGLE_BOOKMARK_LOADING = "TOGGLE_BOOKMARK_LOADING";
export const TOGGLE_BOOKMARK_SUCCESS = "TOGGLE_BOOKMARK_SUCCESS";
export const TOGGLE_BOOKMARK_FAIL = "TOGGLE_BOOKMARK_FAIL";

// Toggle Answer Later
export const TOGGLE_ANSWER_LATER_LOADING = "TOGGLE_ANSWER_LATER_LOADING";
export const TOGGLE_ANSWER_LATER_SUCCESS = "TOGGLE_ANSWER_LATER_SUCCESS";
export const TOGGLE_ANSWER_LATER_FAIL = "TOGGLE_ANSWER_LATER_FAIL";

// Logged in user get following and follower
export const GET_MY_FOLLOWERS_LOADING = "GET_MY_FOLLOWERS_LOADING";
export const GET_MY_FOLLOWERS_SUCCESS = "GET_MY_FOLLOWERS_SUCCESS";
export const GET_MY_FOLLOWERS_FAIL = "GET_MY_FOLLOWERS_FAIL";
export const GET_MY_FOLLOWINGS_LOADING = "GET_MY_FOLLOWINGS_LOADING";
export const GET_MY_FOLLOWINGS_SUCCESS = "GET_MY_FOLLOWINGS_SUCCESS";
export const GET_MY_FOLLOWINGS_FAIL = "GET_MY_FOLLOWINGS_FAIL";

// Bookmarks
export const GET_MY_BOOKMARKS_LOADING = "GET_MY_BOOKMARKS_LOADING";
export const GET_MY_BOOKMARKS_SUCCESS = "GET_MY_BOOKMARKS_SUCCESS";
export const GET_MY_BOOKMARKS_FAIL = "GET_MY_BOOKMARKS_FAIL";

// Answer Later
export const GET_MY_ANSWER_LATER_LOADING = "GET_MY_ANSWER_LATER_LOADING";
export const GET_MY_ANSWER_LATER_SUCCESS = "GET_MY_ANSWER_LATER_SUCCESS";
export const GET_MY_ANSWER_LATER_FAIL = "GET_MY_ANSWER_LATER_FAIL";

// Timeline Posts
export const GET_TIMELINE_POSTS_LOADING = "GET_TIMELINE_POSTS_LOADING";
export const GET_TIMELINE_POSTS_SUCCESS = "GET_TIMELINE_POSTS_SUCCESS";
export const GET_TIMELINE_POSTS_FAIL = "GET_TIMELINE_POSTS_FAIL";

// Any Upvote Solution
export const UPVOTE_SOLUTION_ANY_LOADING = "UPVOTE_SOLUTION_ANY_LOADING";
export const UPVOTE_SOLUTION_ANY_SUCCESS = "UPVOTE_SOLUTION_ANY_SUCCESS";
export const UPVOTE_SOLUTION_ANY_FAIL = "UPVOTE_SOLUTION_ANY_FAIL";

// Any Downvote Solution
export const DOWNVOTE_SOLUTION_ANY_LOADING = "DOWNVOTE_SOLUTION_ANY_LOADING";
export const DOWNVOTE_SOLUTION_ANY_SUCCESS = "DOWNVOTE_SOLUTION_ANY_SUCCESS";
export const DOWNVOTE_SOLUTION_ANY_FAIL = "DOWNVOTE_SOLUTION_ANY_FAIL";

// Any Upvote Question
export const UPVOTE_QUESTION_ANY_LOADING = "UPVOTE_QUESTION_ANY_LOADING";
export const UPVOTE_QUESTION_ANY_SUCCESS = "UPVOTE_QUESTION_ANY_SUCCESS";
export const UPVOTE_QUESTION_ANY_FAIL = "UPVOTE_QUESTION_ANY_FAIL";

// Any Downvote Question
export const DOWNVOTE_QUESTION_ANY_LOADING = "DOWNVOTE_QUESTION_ANY_LOADING";
export const DOWNVOTE_QUESTION_ANY_SUCCESS = "DOWNVOTE_QUESTION_ANY_SUCCESS";
export const DOWNVOTE_QUESTION_ANY_FAIL = "DOWNVOTE_QUESTION_ANY_FAIL";

// Get Top Users
export const GET_TOP_USERS_LOADING = "GET_TOP_USERS_LOADING";
export const GET_TOP_USERS_SUCCESS = "GET_TOP_USERS_SUCCESS";
export const GET_TOP_USERS_FAIL = "GET_TOP_USERS_FAIL";

// Interested Categories
export const CHOOSE_INTERESTED_CATEGORY_LOADING =
  "CHOOSE_INTERESTED_CATEGORY_LOADING";
export const CHOOSE_INTERESTED_CATEGORY_SUCCESS =
  "CHOOSE_INTERESTED_CATEGORY_SUCCESS";
export const CHOOSE_INTERESTED_CATEGORY_FAIL =
  "CHOOSE_INTERESTED_CATEGORY_FAIL";

//Suggested Categories
export const SUGGEST_MISSING_CATEGORIES_LOADING =
  "SUGGEST_MISSING_CATEGORIES_LOADING";
export const SUGGEST_MISSING_CATEGORIES_SUCCESS =
  "SUGGEST_MISSING_CATEGORIES_SUCCESS";
export const SUGGEST_MISSING_CATEGORIES_FAIL =
  "SUGGEST_MISSING_CATEGORIES_FAIL";
