// Authentication USING OAUTH
export const LOGIN_WITH_OAUTH_LOADING = "LOGIN_WITH_OAUTH_LOADING";
export const LOGIN_WITH_OAUTH_SUCCESS = "LOGIN_WITH_OAUTH_SUCCESS";
export const LOGIN_WITH_OAUTH_FAIL = "LOGIN_WITH_OAUTH_FAIL";

// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// Login Using Email
export const LOGIN_WITH_EMAIL_LOADING = "LOGIN_WITH_EMAIL_LOADING";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAIL = "LOGIN_WITH_EMAIL_FAIL";

// Register Using Email
export const REGISTER_WITH_EMAIL_LOADING = "REGISTER_WITH_EMAIL_LOADING";
export const REGISTER_WITH_EMAIL_SUCCESS = "REGISTER_WITH_EMAIL_SUCCESS";
export const REGISTER_WITH_EMAIL_FAIL = "REGISTER_WITH_EMAIL_FAIL";
export const RESET_EMAIL_SUCCESS_MESSAGE = "RESET_EMAIL_SUCCESS_MESSAGE";

// Me Loading
export const ME_LOADING = "ME_LOADING";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAIL = "ME_FAIL";

export const GET_FEATURE = "GET_FEATURE";
export const GET_PROFILE = "GET_PROFILE";

export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const EDIT_USER_LOADING = "EDIT_USER_LOADING";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// Post solution
export const POST_SOLUTION_REQUEST = "POST_SOLUTION_REQUEST";
export const POST_SOLUTION_SUCCESS = "POST_SOLUTION_SUCCESS";
export const POST_SOLUTION_FAIL = "POST_SOLUTION_FAIL";

// Questions
export const ASK_QUESTION_LOADING = "ASK_QUESTION_LOADING";
export const ASK_QUESTION_SUCCESS = "ASK_QUESTION_SUCCESS";
export const ASK_QUESTION_FAIL = "ASK_QUESTION_FAIL";

// Tags
export const GET_ALL_TAGS_LOADING = "GET_ALL_TAGS_LOADING";
export const GET_ALL_TAGS_SUCCESS = "GET_ALL_TAGS_SUCCESS";
export const GET_ALL_TAGS_FAIL = "GET_ALL_TAGS_FAIL";

// view solution
export const VIEW_SOLUTION_LOADING = "VIEW_SOLUTION_LOADING";
export const VIEW_SOLUTION_SUCCESS = "VIEW_SOLUTION_SUCCESS";
export const VIEW_SOLUTION_FAIL = "VIEW_SOLUTION_FAIL";

//all solutions
export const GET_ALL_SOLUTIONS_LOADING = "GET_ALL_SOLUTIONS_LOADING";
export const GET_ALL_SOLUTIONS_SUCCESS = "GET_ALL_SOLUTIONS_SUCCESS";
export const GET_ALL_SOLUTIONS_FAIL = "GET_ALL_SOLUTIONS_FAIL";

//upvote solution
export const UPVOTE_SOLUTION_LOADING = "UPVOTE_SOLUTION_LOADING";
export const UPVOTE_SOLUTION_SUCCESS = "UPVOTE_SOLUTION_SUCCESS";
export const UPVOTE_SOLUTION_FAIL = "UPVOTE_SOLUTION_FAIL";

//downvote solution
export const DOWNVOTE_SOLUTION_LOADING = "DOWNVOTE_SOLUTION_LOADING";
export const DOWNVOTE_SOLUTION_SUCCESS = "DOWNVOTE_SOLUTION_SUCCESS";
export const DOWNVOTE_SOLUTION_FAIL = "DOWNVOTE_SOLUTION_FAIL";
