export const question = [
    "How to become doctor without medical license?",
    "How to become doctor without medical license?",
    "how to apply for car licence?",
    "Is there any possibilities that Ranjit can have a baby?",
    "How to apply for passport?",	
    "How to become doctor without medical license?",
    "How can I apply for australian visa?",
    "Is there any possibilities that Ranjit can have a baby?",
    "How to become a Prime Minister?",
    "How to become doctor without medical license?",
    "Is there any possibilities that Ranjit can have a baby?",
    "Why does Ranjit goes to love dara everyday?",
    "When will Samir become a mother?",
    "HOw to make a online payment?",
    "How can I apply for australian visa?",
    "How to apply for visa?",	
    "How to become a Prime Minister?",
    "How to become doctor without medical license?",
    "Is there any possibilities that Ranjit can have a baby?",
    "Why does Ranjit goes to love dara everyday?",
    "When will Samir become a mother?",
    "How to become a Prime Minister?",
    "How to become doctor without medical license?",
    "Is there any possibilities that Ranjit can have a baby?",
    "Why does Ranjit goes to love dara everyday?",
    "When will Samir become a mother?",
  ];
  